### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by yo1frenchtoast** [yo1frenchtoast/hermod-api#2]
After some minutes/hours, process inside web container shows a high level of CPU usage (~150%), with ou without debug mode enabled

**Comment by yo1frenchtoast** [comment]
```
AttributeError: module 'urllib' has no attribute 'quote'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rq/worker.py", line 822, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 605, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 611, in _execute
    return self.func(*self.args, **self.kwargs)
  File "./telegram.py", line 11, in send
    url = 'https://api.telegram.org/bot'+token+'/sendMessage?chat_id='+str(chatid)+'&text='+urllib.quote(message)
AttributeError: module 'urllib' has no attribute 'quote'
```

Fix => https://github.com/yo1frenchtoast/hermod-api/commit/959852297b4e7993c609bf59405aa4c76efa34df

**Comment by yo1frenchtoast** [comment]
https://github.com/yo1frenchtoast/hermod-api/commit/d90209d2316771930688416f9981b2dde100cfb6

**Comment by yo1frenchtoast** [comment]
Failure on sms send caused a loop in main program => added try/exept to avoid
