### ISSUE TITLE
Loop on main api function caused by sql error

### ISSUE THREAD

**Issue by yo1frenchtoast** [yo1frenchtoast/hermod-api#3]
```
08:02:26 default: dbdriver.insert('hosts', {'address': '192.168.x.1', 'mac': 'XX:XX:XX:XX:XX', 'status': 'up', 'last_up': 'apr/23/2020 10:02:26', 'witness': 'router1, 'name': 'host1', 'last_down': 'apr/23/2020 10:02:26'}) (e38f39aa-c445-438a-b582-8677f693e740)
08:02:27 ValueError: Could not process parameters
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rq/worker.py", line 822, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 605, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 611, in _execute
    return self.func(*self.args, **self.kwargs)
  File "./dbdriver.py", line 54, in insert
    cursor.execute(query, data.values())
  File "/usr/local/lib/python3.7/site-packages/mysql/connector/cursor_cext.py", line 248, in execute
    prepared = self._cnx.prepare_for_mysql(params)
  File "/usr/local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 615, in prepare_for_mysql
    raise ValueError("Could not process parameters")
ValueError: Could not process parameters
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rq/worker.py", line 822, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 605, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 611, in _execute
    return self.func(*self.args, **self.kwargs)
  File "./dbdriver.py", line 54, in insert
    cursor.execute(query, data.values())
  File "/usr/local/lib/python3.7/site-packages/mysql/connector/cursor_cext.py", line 248, in execute
    prepared = self._cnx.prepare_for_mysql(params)
  File "/usr/local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 615, in prepare_for_mysql
    raise ValueError("Could not process parameters")
ValueError: Could not process parameters
```

**Comment by yo1frenchtoast** [comment]
34443a3433d89a876426d3c4b42332fd9293187d
